---
- name: System WLAN install wpa_supplicant
  ansible.builtin.apt:
    name: wpasupplicant
    state: present
- name: System WLAN install packages
  ansible.builtin.apt:
    name: "{{ system_wlan_packages }}"
    state: present
  when: (system_wlan_packages | length) > 0