---
- name: get wpa passphrase
  command:
    cmd: "wpa_passphrase {{ network }} {{ password }}"
  timeout: 3
  register: wpa_passphrase
  changed_when: false
- name: set output variable
  set_fact:
    "{{ psk | default('psk') }}": "{{ wpa_passphrase.stdout | regex_search('\\s+psk=(.*)\\n', '\\1') | first }}"
