---
argument_specs:
  # roles/system-user/tasks/main.yml entry point
  main:
    short_description: Main entry point for the system-user role
    description:
      - This is the main entrypoint for the System User configuration role.
      - Role is used to configure single user and optionally group for the system.
    author:
      - Boguslaw Rymut
    options:
      state:
        type: "str"
        chocies:
          - "present"
          - "absent"
        default: "present"
        description: "Create/Update user or delete user"
      name:
        type: "str"
        required: false
        default: "ansible"
        description: "User name to be used"
      uid:
        type: "int"
        required: false
        description: "UID of the user"
      password:
        type: "str"
        required: false
        default: "ansible"
        description: "Password for username"
      group:
        type: "str"
        required: false
        default: "ansible"
      gid:
        type: "int"
        required: false
        description: "Group ID"
      shell:
        type: "str"
        required: false
        default: "/bin/bash"
        description: "Shell used by user"
