---
- name: "Group {{ group }}"
  become: yes
  ansible.builtin.group:
    name: "{{ group }}"
    gid: "{{ gid if gid is not none else omit }}"
    state: present
  when: group

- name: "User {{ name }}"
  become: yes
  ansible.builtin.user:
    name: "{{ name }}"
    state: "{{ state }}"
    system: yes
    create_home: true
    update_password: on_create
    password: "{{ password | password_hash('sha512') }}"
    group: "{{ group }}"
    shell: "{{ shell }}"
    uid: "{{ uid if uid is not none else omit }}"
