---
- name: "Group {{ system_user__group_name }}"
  become: yes
  ansible.builtin.group:
    name: "{{ system_user__group_name }}"
    gid: "{{ system_user__group_id | default(omit) }}"
    state: present
  when: system_user__group_name is defined

- name: "User {{ system_user__name }}"
  become: yes
  ansible.builtin.user:
    name: "{{ system_user__name }}"
    state: "{{ system_user__state }}"
    system: yes
    create_home: true
    password: "{{ system_user__password | password_hash('sha512') }}"
    group: "{{ system_user__group_name | default(omit) }}"
    shell: "{{ system_user__shell }}"
    uid: "{{ system_user__id | default(omit) }}"
