---
- name: Install powertop
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Create powertop service
  ansible.builtin.import_role:
    name: buluma.service
  vars:
    service_list:
      - name: "{{ name }}"
        description: Powertop
        start_command: /usr/sbin/powertop --auto-tune
        type: oneshot

- name: Enable powertop
  ansible.builtin.service:
    name: "{{ name }}"
    state: stopped
    enabled: true