---
- name: Remove network configuration
  file:
    state: absent
    path: "{{ system_network_interfaces_path }}"
  when: system_network_state == 'absent'

- name: Create network configuration
  template:
    src: interfaces.j2
    dest: "{{ system_network_interfaces_path }}"
  when: system_network_state == 'present'
