---
---
- file:
    state: absent
    path: "{{ system_network_interfaces_path }}"
  when: system_network_state == 'absent'
- meta: end_play
  when: system_network_state != 'present'
- template:
    src: interfaces.j2
    dest: "{{ system_network_interfaces_path }}"
